version: '3.8'

services:
  # Contenedor 1: Base de datos SQL (PostgreSQL)
  db:
    image: postgres:13-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always

  # Contenedor 2: Aplicación en Python
  app:
    build: .
    container_name: python_app
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
    depends_on:
      - db